/* eslint-disable prettier/prettier */
export const ScreenKey = {
  HomeScreen: 'homeScreen',
  Setting:'setting',
  TeacherDetail: 'teacherDetail',
  TeacherSchedule: 'teacherSchedule',
  MessageDialog: 'messageDialog',
  Room: 'room',
  UpcomingScreen: 'upcomingScreen',
  MessageScreen: 'messageScreen',
  TeachersScreen: 'teachersScreen',
  SettingScreen: 'settingScreen',
  Profile: 'profile',
  EditProfile: 'editProfile',
  Feedback: 'feedback',
  BookingHistory: 'bookingHistory',
  SessionHistory: 'sessionHistory',
  AdvancedSetting: 'advancedSetting',
  BecomeATeacher: 'becomeATeacher',
  Session: 'session',
  CourseDetail: 'courseDetail',
  CoursesScreen: 'coursesScreen',
  ForgetPassword: 'forgetPassword',
  Register: 'register',
  Login: 'login',
  Courses: 'Courses',
  Teachers: 'Teachers',
  Schedule: 'Schedule',
  Message: 'Message',
  Home: 'Home',
  HomeTabs: 'homeTabs',
};
