/* eslint-disable prettier/prettier */
export const bookingHistory = [
    {
        id: 1,
        name: 'Duong Pham',
        date: '14-02-2022',
        timeStart: '08:00',
        timeEnd: '10:00',
        isOver: true,
    },
    {
        id: 2,
        name: 'Hai Nguyen',
        date: '14-02-2022',
        timeStart: '08:00',
        timeEnd: '10:00',
        isOver: true,
    },
    {
        id: 3,
        name: 'Tuam Pham',
        date: '14-02-2022',
        timeStart: '08:00',
        timeEnd: '10:00',
        isOver: true,
    },
    {
        id: 4,
        name: 'An Nguyen',
        date: '14-02-2022',
        timeStart: '08:00',
        timeEnd: '10:00',
        isOver: false,
    },
    {
        id: 5,
        name: 'Duc Nguyen',
        date: '14-02-2022',
        timeStart: '08:00',
        timeEnd: '10:00',
        isOver: false,
    },
    {
        id: 6,
        name: 'Quynh Pham',
        date: '14-02-2022',
        timeStart: '08:00',
        timeEnd: '10:00',
        isOver: false,
    },
    {
        id: 7,
        name: 'Duong Nguyen',
        date: '14-02-2022',
        timeStart: '08:00',
        timeEnd: '10:00',
        isOver: false,
    },
];
